#!/bin/bash
LOCALHOME=$(echo ~)
STAMP=$(date +%y%m%d%H%M)
DISTRO=ubuntu

if [ -n "$1" ] ; then
   VERSION=$1
fi

if [ -z "$VERSION" ] ; then
    VERSION=14.04
fi
#VERSION=16.04
IMAGE=jpuhlman/$DISTRO-mirror:v$VERSION
IMAGE=$DISTRO-mirror:v$VERSION
PULL_IMAGE="1"
if [ -z "$USER" ] ; then
    USER=mirroradm
fi
MOCK_REQUIREMENTS="--privileged \
                  --cap-add=SYS_ADMIN \
                  --security-opt seccomp:unconfined \
                  --security-opt label:disable \
"
USER_ENVIORNMENT="--hostname $HOSTNAME \
                 -e USERID=$(id -u) \
                 -e USERGID=$(id -g) \
                 -e USERNAME=$USER \
                 -e HOME=$LOCALHOME \
                 -e LANG=en_US.UTF-8 \
                 -e CURRENTPATH=$(pwd) \
                 -v $LOCALHOME:$LOCALHOME \
                 -v $(pwd):/var/spool/apt-mirror \
                 "

DOCKER_ACCESS="-v /var/run/docker.sock:/var/run/docker.sock"
if [ -e $LOCALHOME/.$DISTRO-builder ] ; then
    source $LOCALHOME/.$DISTRO-builder
fi
if [ "$PULL_IMAGE" = "1" ] ; then
     docker pull $IMAGE
fi
 docker run -it \
    --name $DISTRO-$VERSION-$STAMP \
    $MOCK_REQUIREMENTS \
    $DOCKER_ACCESS \
    $USER_ENVIORNMENT \
    $EXTRA_DOCKER_CONFIGS \
    $SCRIPTRUNNER \
    $IMAGE
 docker rm $DISTRO-$VERSION-$STAMP
